services:

  db_container_5:
    image: postgres:15-alpine
    container_name: postgres_credits_v5
    restart: always
    environment:

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5435:5432"
    volumes:
      - credits_data_v5:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app_v5
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db_container_5

volumes:

  credits_data_v5: